// General Use
export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';

// Contact types
export const GET_CONTACTS = 'GET_CONTACTS';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CONTACT_ERROR = 'CONTACT_ERROR';

// Wallet types
export const WALLET_SETBALANCE = 'WALLET_SETBALANCE';
export const WALLET_NEW = 'WALLET_NEW';
export const WALLET_LOAD = 'WALLET_LOAD';
export const WALLET_LOADING = 'WALLET_LOADING';
export const WALLET_LOADED = 'WALLET_LOADED';
export const WALLET_RESTOREFROMKEY = 'WALLET_RESTOREFROMKEY';
export const WALLET_GETBALANCE = 'WALLET_GETBALANCE';
export const WALLET_ADDCHILD = 'WALLET_ADDCHILD';
export const WALLET_ENCRYPTED = 'WALLET_ENCRYPTED';
export const WALLET_SETHANDLERS = 'WALLET_SETHANDLERS';
export const WALLET_SETLOADHANDLER = 'WALLET_SETLOADHANDLER';
export const WALLET_SETBALANCEHANDLER = 'WALLET_SETBALANCEHANDLER';
export const WALLET_SETCREATEWALLETHANDLER = 'WALLET_SETCREATEWALLETHANDLER';
export const WALLET_SETCREATECHILDHANDLER = 'WALLET_SETCREATECHILDHANDLER';

// Auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// User types
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
